# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identities',
            old_name='os',
            new_name='opsys',
        ),
    ]
