# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_auto_20180313_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
