# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='identities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('ips', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
            ],
        ),
    ]
